<?php 
/**
 * Layout de base pour toute la présentation su site
 * @author CONRAD Pascal
 * @version 1.0 14/04/2014
 */

  $this->doctype('HTML5');
  echo $this->doctype();
?>
<html>
<head>
 <?php echo $this->headTitle($this->translate('title1','search')); ?>
 <?php 
$this->headLink()->headLink(array('rel' => 'shortcut icon','type' => 'image/vnd.microsoft.icon','href' => $this->basePath()."img/favicon.ico"),'PREPEND')
				 ->prependStylesheet($this->basePath().'/css/blueprint/screen.css','screen')
				 ->prependStylesheet($this->basePath().'/css/blueprint/print.css','print')
				 ->prependStylesheet($this->basePath().'/css/main-theme.css')
                 ->prependStylesheet($this->basePath().'/css/jquery-ui.css');
$this->headScript()->appendFile($this->basepath().'/js/jquery.js')
                   ->appendFile($this->basepath().'/js/jquery-ui.js')
                   ->appendFile($this->basepath().'/js/main_function.js');
$this->headmeta()->setCharset('UTF-8');
$this->headmeta()->appendHttpEquiv('pragma','no-cache')
                 ->appendHttpEquiv('Content-Language','fr_FR');

echo $this->headmeta();
echo $this->headLink();
echo $this->headScript();

?>
</head>
<body>
<div class='container'>
 <?php echo $this->appHeader; ?>
 <div class='span-6'><?php echo $this->appMenu; ?></div>
 <div class='span-18 last'><?php echo $this->content; ?></div>
 <?php echo $this->appFooter; ?>
</div>
</body>
</html>
