<div class='display_zone'>
<?php
	if ($this->action=='add') $form->setAttribute('action',$this->url('mcontact'));
	$form->setAttribute('method','post');
	$form->prepare();
	echo $this->form()->opentag($form);
?>
<div class='infoMessageTo'>
<?php echo $this->translate('messageEdit_To','message'); ?> : administrateur kiamapiece<br>
</div>
<div class='editor'>
<?php echo $this->formTextarea($form->get('Message'));?>
</div>
<a class='buttonType' id='btSubmit' data-client='message' data-role='add'><?php echo $this->translate('messageSend','message')?></a>
<?php echo $this->form()->closetag($form); ?>
</div>
