<p class='mention_title'>Mention légale</p>
<div class='mention_infos_legales'>kiamapiece.fr - Administrateur du site, CONRAD Pascal - le 28/03/2015<br>
<br>
Les informations recueillies font l’objet d’un traitement informatique destiné à facilité l'échange entre individus afin de proposé des pièces d'appareils électroménager.<br> 
Les destinataires des données sont : uniquement les personnes inscrite à ce site, partiellement ou complète après acceptation de celui-ci.<br>
<br>
Conformément à la loi « informatique et libertés » du 6 janvier 1978 modifiée en 2004, vous bénéficiez d’un droit d’accès et de rectification aux informations qui vous concernent, que vous pouvez exercer en vous adressant à <a>administrateur@kiamapiece.fr</a><br>
<br>
Vous pouvez également, pour des motifs légitimes, vous opposer au traitement des données vous concernant.<br>
<br>
Un cookie est enregistré sur votre ordinateur. Il a pour but de maintenir votre session ouverte et rien d'autre. 
</div>
<p class='mention_title'>Informations sur les outils</p>
<ul>
<li>Framework Zend 2 : http://framework.zend.com/ - licence : BSD modifié <a href='http://fr.wikipedia.org/wiki/Licence_BSD' title='Licence BSD'>http://fr.wikipedia.org/wiki/Licence_BSD</a></li>
<li>ORM : Doctrine 2 : http://www.doctrine-project.org/ - licence : GNU/GPL <a href='http://fr.wikipedia.org/wiki/GNU_LGPL' title='Licence GNU/GPL'>http://fr.wikipedia.org/wiki/GNU_LGPL</a></li>
<li>CSS : blueprint : http://www.blueprintcss.org/ - licence MIT modifié <a href='licence http://fr.wikipedia.org/wiki/Licence_MIT' title='Licence MIT'>http://fr.wikipedia.org/wiki/Licence_MIT</a></li>
<li>jQuery - http://jquery.com/ licence MIT <a href='licence http://fr.wikipedia.org/wiki/Licence_MIT' title='Licence MIT'>http://fr.wikipedia.org/wiki/Licence_MIT</a>&nbsp;,GNU&nbsp;GPL<a href='http://fr.wikipedia.org/wiki/GNU_LGPL' title='Licence GNU/GPL'>http://fr.wikipedia.org/wiki/GNU_LGPL</a></li>
</ul>