<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Request\Module'                        => __DIR__ . '/Module.php',
    'Request\Controller\RequestController' => __DIR__ . '/src/Request/Controller/RequestController.php',
    'RequestTest\Framework\TestCase'        => __DIR__ . '/tests/Request/Framework/TestCase.php',
    'RequestTest\SampleTest'                => __DIR__ . '/tests/Request/SampleTest.php',
);
