<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Contact\Module'                        => __DIR__ . '/Module.php',
    'Contact\Controller\ContactController' => __DIR__ . '/src/Contact/Controller/ContactController.php',
    'ContactTest\Framework\TestCase'        => __DIR__ . '/tests/Contact/Framework/TestCase.php',
    'ContactTest\SampleTest'                => __DIR__ . '/tests/Contact/SampleTest.php',
);
