<div id='userForm'>
<?php 

if ($this->action=='add') $form->setAttribute('action',$this->url('adr/'.$this->action));else $form->setAttribute('action',$this->url('adr/'.$this->action,array('id' => $this->id)));
$form->setAttribute('method','post');
$form->prepare();

echo $this->form()->openTag($form);
if ($this->action!='add') echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('csrf'));
echo $this->myFormRow($form->get('AddressName'));
echo $this->myFormRow($form->get('Number'));
echo $this->myFormRow($form->get('Street'));
echo $this->myFormRow($form->get('Complement'));
echo $this->myFormRow($form->get('PostalCode'));
echo $this->myFormRow($form->get('Town'));
echo $this->myFormRow($form->get('RegionId'));
?>
<a class='buttonType' href='<?php echo $this->basePath().'/user/view'; ?>'><?php echo $this->translate('backToSearch','user'); ?></a>
<a class='buttonType' id='btSubmit' data-client='adr' data-role='<?php echo $this->action; ?>'>enregistre</a>
<?php echo $this->form()->closeTag();?>
</div>

