<div class='formUser'>
<?php 
$form->setAttribute('action',$this->url('user/lostpwd'));
$form->setAttribute('method','post');
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php echo $this->translate('LostPwd_Message','user');?><br>
<br>
<?php
  echo $this->formHidden($form->get('csrf'));
  echo $this->MyFormRow($form->get('Email'));
?>
<br>
<a class='buttonType' id='btSubmit' data-client='user' data-role='lpemail' href='#' title='<?php echo $this->translate('LostPwd_TitleButtonSend','user'); ?>'><?php echo $this->translate('LostPwd_ButtonSend','user'); ?></a>
<?php echo $this->form()->closeTag();?>
</div>
