<table>
<tr><th><?php echo $this->translate('messageList_From','message'); ?></th><th><?php echo $this->translate('messageList_To','message'); ?></th><th><?php echo $this->translate('messageList_Date','message'); ?></th><th><?php echo $this->translate('messageList_Piece','message'); ?></th></tr>
<?php foreach($this->messages as $message) :?>
	<tr>
	<?php if ($message->getUserFrom()->getId()==$this->me) :?>
		<td><a href='<?php echo $this->basePath().'/message/view/'.$message->getId(); ?>'><?php echo $this->translate('messageList_Me','message'); ?></a></td>
		<td><?php echo $message->getUserTo()->getPseudo();?>
	<?php else :?>
		<td><a href='<?php echo $this->basePath().'/message/view/'.$message->getId(); ?>'><?php echo $message->getUserFrom()->getPseudo();?></a></td>
		<td><?php echo $this->translate('messageList_Me','message'); ?></td>
	<?php endif;?>
    <td><?php echo $message->getCreateDate()->format('d/m/Y'); ?></td>
	<td><?php
	$msg=$this->translate('messageList_Piece','message');
	$msg.=" marque ".$message->getPiece()->getBrand()->Description;
	$msg.=" type".$message->getPiece()->getApplianceType()->Description;
	echo $msg;
	?></td>
	</tr>
<?php endforeach?>
</table>
