<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Piece\Module'                        => __DIR__ . '/Module.php',
    'Piece\Controller\PieceController' => __DIR__ . '/src/Piece/Controller/PieceController.php',
    'PieceTest\Framework\TestCase'        => __DIR__ . '/tests/Piece/Framework/TestCase.php',
    'PieceTest\SampleTest'                => __DIR__ . '/tests/Piece/SampleTest.php',
);
