<div id='Search_View'>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_name','search')?></span><span class='iText'><?php echo $this->pieces->User->Name;?></span></div>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_town','search')?></span><span class='iText'><?php echo $this->pieces->Address->Town;?></span></div>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_brand','search')?></span><span class='iText'><?php echo $this->pieces->Brand->Description;?></span></div>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_apt','search')?></span><span class='iText'><?php echo $this->pieces->ApplianceType->Description;?></span></div>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_pct','search')?></span><span class='iText'><?php echo $this->pieces->PieceType->Description;?></span></div>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_comment','search')?></span><span class='iText'><?php echo $this->pieces->Comments;?></span></div>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_date','search')?></span><span class='iText'><?php echo $this->pieces->CreateDate->format("d/m/Y");?></span></div>
</div>
