<div id='headerBlock' class='span-18'>
<img src='<?php echo $this->basepath('img/kiamapiece.png')?>' title='kiamapiece'>
</div>
<div class='span-6 last'>
<div id='loginBox'>
<div id='connectBox'>
<label>email :</label><input type="text" name='loginEmail' value=''><br>
<label><?php echo $this->translate('logPassword','search'); ?></label><input type="text" name='loginPassword' value='' size="10"><br>
<a href='#' id='btLogin'><?php echo $this->translate('connect','search')?></a>
</div>
<div id='infoLogin' style='display : none'>Bonjour<br></div>
</div>
</div>
<div class='span-24'>
<div id='leitmotivBlock' ><?php echo $this->translate('leitmotiv','search'); ?></div>
</div>