<div id='Search_View'>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_name','search')?></span><span class='iText'><?php echo $this->pieces->getUser()->getPseudo();?></span></div>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_town','search')?></span><span class='iText'><?php echo $this->pieces->getAddress()->Town;?></span></div>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_brand','search')?></span><span class='iText'><?php echo $this->pieces->getBrand()->Description;?></span></div>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_apt','search')?></span><span class='iText'><?php echo $this->pieces->getApplianceType()->Description;?></span></div>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_pct','search')?></span><span class='iText'><?php echo $this->pieces->getPieceType()->Description;?></span></div>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_comment','search')?></span><span class='iTextarea'><?php echo $this->pieces->getComments();?></span></div>
<div id='iRow'><span class='iLabel'><?php echo $this->translate('search_view_date','search')?></span><span class='iText'><?php echo $this->pieces->getCreateDate()->format("d/m/Y");?></span></div>
<br>
<a id='btBack' class='buttonType' href='<?php echo $this->url('search'); ?>'>Retour</a><a id='btDo' class='buttonType' href='<?php echo $this->basePath().'/request/do/'.$this->pieces->getId(); ?>'>Cette pièce m'interesse</a>
</div>
